basePath: /
definitions:
  api.healthCheck:
    properties:
      code:
        description: API return code
        example: SUCCESS
        type: string
      health:
        description: Health status of the service
        example: RUNNING
        type: string
    type: object
  api.user:
    properties:
      code:
        description: API return code
        example: SUCCESS
        type: string
      user:
        $ref: '#/definitions/entity.User'
        description: informations of a user
        type: object
    type: object
  entity.User:
    properties:
      created_at:
        description: creation date of the entry (format example 2019-01-17T21:03:08.373394+01:00)
        example: "2019-01-17T21:03:08.373394+01:00"
        type: string
      first_name:
        example: John
        type: string
      id:
        description: id of the User (format UUID)
        example: 8da8adc3-0ae9-47b2-884c-ee41e691ff57
        type: string
      last_name:
        example: Doe
        type: string
      updated_at:
        description: last update date of the entry (format example 2019-01-17T21:03:08.373394+01:00)
        example: "2019-01-17T21:03:08.373394+01:00"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Thomas Poignant
    url: https://github.com/thomaspoignant/user-microservice/
  description: user-microservice is a set of API to manage users
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Swagger user-microservice
  version: "1.0"
paths:
  /health:
    get:
      description: health check endpoint to know if the service is up
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.healthCheck'
            type: object
      summary: Health check endpoint
      tags:
      - healthcheck
  /v1/user/{id}:
    get:
      parameters:
      - description: Bottle ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.user'
            type: object
      summary: test swagger
      tags:
      - user
swagger: "2.0"
